# NumPy Lab Exercises 

Solve the following questions in Lab to test your knowledge on NumPy Package!

#### Import NumPy package as np

In [1]:
import numpy as np

#### Create an array of 20 0's 

In [2]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### Create an array of 20 1's

In [3]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

#### Create an array containing 30 sixes

In [4]:
6 * np.ones(30)

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

#### Create an array of integers starting from 21 until 31

In [6]:
np.arange(21, 32)

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

#### Create an array of all even integers from 2 to 60

In [7]:
np.arange(2, 62, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

#### Create a 5x6 matrix with values ranging from 0 to 29

In [13]:
np.arange(0, 30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

#### Create an identity matrix of shape 5x5

In [9]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Use NumPy to generate a random set of 10 numbers between 0 and 1

In [18]:
np.random.rand(10)

array([0.50770925, 0.14792013, 0.04152056, 0.90692193, 0.19461593,
       0.21407815, 0.18212397, 0.4713832 , 0.81230007, 0.72993328])

#### Use NumPy to generate an array of 15 random numbers sampled from a standard normal distribution

In [19]:
np.random.randn(15)

array([ 0.45919317, -1.43394942,  1.45540819, -2.42350382,  1.10626829,
       -0.3348236 , -1.02476584,  0.3532068 , -1.94993022, -2.4501658 ,
       -0.77376447, -1.67972821, -0.48222699,  0.0778819 , -1.98615223])

#### Create the following 5x10 matrix with the values using arange,reshape and arithmetic operators:

In [22]:
np.arange(0.01, 0.51, 0.01).reshape(5, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ]])

#### Create an array of 30 linearly spaced points between 0 and 10:

In [23]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## Numpy Indexing and Selections

Using the below given Matrix, generate the output for the below questions

In [24]:
simple_matrix = np.arange(1,101).reshape(10,10)
simple_matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

#### Retrieve the last 2 rows and first 3 column values of the above matrix using index & selection technique

In [30]:
simple_matrix[-2:, :3]

array([[81, 82, 83],
       [91, 92, 93]])

#### Retrieve the value 55 from the above matrix using index & selection technique

In [31]:
simple_matrix[5, 4]

55

#### Retrieve the values from the 3rd column in the above matrix

In [33]:
simple_matrix[:, 2]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

#### Retrieve the values from the 4th row in the above matrix

In [34]:
simple_matrix[3, :]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

#### Retrieve values from the 2nd & 4th rows in the above matrix

In [38]:
simple_matrix[[2,4], :]

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

### Calculate the following values for the given matrix

#### Calculate sum of all the values in the matrix

In [39]:
simple_matrix.sum()

5050

#### Calculate standard deviation of all the values in the matrix

In [40]:
simple_matrix.std()

28.86607004772212

#### Calculate the variance of all values in the matrix

In [41]:
simple_matrix.var()

833.25

#### Calculate the mean of all values in the matrix

In [42]:
simple_matrix.mean()

50.5

### End of Lab Exercise - NumPy